FROM ubuntu:20.04

RUN apt-get update && apt-get install -y gnupg 

# ADD resources/sources.list /etc/apt/

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ABF5BD827BD9BF62
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FEEA9169307EA071

RUN echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu focal main" >> /etc/apt/sources.list
RUN echo "deb-src http://ppa.launchpad.net/ondrej/php/ubuntu focal main" >> /etc/apt/sources.list

RUN apt-get update && apt-get install -y --option Acquire::Retries=100 --option Acquire::http::Timeout="60" \
    php8.1-fpm \ 
    php8.1-common \ 
    php8.1-curl \ 
    php8.1-pgsql \ 
    php8.1-mysql \ 
    php8.1-mbstring \ 
    php8.1-xml \
    php8.1-xmlrpc \
    php8.1-bcmath \
    php8.1-zip \
    php8.1-zmq \
    php8.1-opcache \
    php8.1-pdo \
    php8.1-gd \
    php8.1-imagick \
    php8.1-ldap \
    php8.1-imap \
    php8.1-intl \
    php8.1-cli \
    php8.1-xdebug 

RUN rm -rf /var/lib/apt/lists/*
#------------- Container Config ---------------------------------------------------------------

# Expose port 8080
EXPOSE 80
CMD [ "bash" ]